# Generated by Django 5.2 on 2025-04-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=120)),
                ('required_skills', models.CharField(max_length=120)),
                ('min_experience_years', models.IntegerField()),
                ('must_have_keywords', models.CharField(max_length=120)),
                ('preferred_education', models.CharField(max_length=120)),
                ('status', models.IntegerField(choices=[(0, 'File uploading'), (1, 'Running'), (2, 'Completed'), (3, 'Failed')], default=0)),
            ],
        ),
    ]
