# Generated by Django 5.2 on 2025-04-10 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='process_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'File uploaded'), (2, 'Completed'), (3, 'Failed')], default=0)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='initiate.process')),
            ],
        ),
    ]
