# Generated by Django 5.2 on 2025-04-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiate', '0002_processfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='processfile',
            name='remarks',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='processfile',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='processfile',
            name='status',
            field=models.IntegerField(choices=[(0, 'File uploaded'), (1, 'Completed'), (2, 'Failed')], default=0),
        ),
    ]
