# Generated by Django 5.2 on 2025-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiate', '0003_processfile_remarks_processfile_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processfile',
            name='candidate_education',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='processfile',
            name='candidate_experience_years',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='processfile',
            name='candidate_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='processfile',
            name='candidate_projects',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='processfile',
            name='candidate_skills',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
